[workspace]
members = ["badge-input", "badge-screen", "firmware", "shared", "web"]
resolver = "2"

[profile.dev]
debug = true
opt-level = "z"

[profile.release]
codegen-units = 1
opt-level = "s"
lto = false

[profile.release.package.rustls]
codegen-units = 16
opt-level = 0

[patch.crates-io]
temporalio-client = { path = "firmware/vendor/temporalio-client-1.0.0" }
temporalio-common = { path = "firmware/vendor/temporalio-common-1.0.0" }
temporalio-sdk = { path = "firmware/vendor/temporalio-sdk-1.0.0" }
temporalio-sdk-core = { path = "firmware/vendor/temporalio-sdk-core-0.9.0" }
